basePath: /api/v1/
definitions:
  responses.JWTResponse:
    properties:
      token:
        type: string
    type: object
  responses.SuccessResponse:
    properties:
      data: {}
      success:
        type: boolean
    type: object
  responses.UserRegisterResponse:
    properties:
      created_at:
        type: string
      email:
        type: string
      first_name:
        type: string
      id:
        type: integer
      last_name:
        type: string
    type: object
  types.AddProduct:
    properties:
      name:
        type: string
      quantity:
        type: integer
    type: object
  types.AddToCart:
    properties:
      id:
        type: integer
      quantity:
        type: integer
    type: object
  types.AddressPayload:
    properties:
      apartment:
        type: integer
      city:
        type: string
      house:
        type: integer
      street:
        type: string
    type: object
  types.CartItem:
    properties:
      name:
        type: string
      price:
        type: number
      quantity:
        type: integer
    type: object
  types.CreateProductPayload:
    properties:
      description:
        type: string
      name:
        type: string
      price:
        type: number
    required:
    - name
    - price
    type: object
  types.ShortProducts:
    properties:
      id:
        type: integer
      name:
        type: string
      price:
        type: number
    type: object
  types.User:
    properties:
      banned:
        type: boolean
      createdAt:
        type: string
      email:
        type: string
      email_verified:
        type: boolean
      firstName:
        type: string
      id:
        type: integer
      lastName:
        type: string
      password:
        type: string
      role:
        type: string
      token:
        type: string
    type: object
  types.UserLoginPayload:
    properties:
      email:
        type: string
      password:
        maxLength: 32
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  types.UserProfile:
    properties:
      address:
        $ref: '#/definitions/types.AddressPayload'
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      password:
        type: string
    type: object
  types.UserRegisterPayload:
    properties:
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      password:
        maxLength: 32
        minLength: 8
        type: string
    required:
    - email
    - firstName
    - lastName
    - password
    type: object
  types.UserUpdatePayload:
    properties:
      firstName:
        type: string
      lastName:
        type: string
      password:
        maxLength: 32
        minLength: 8
        type: string
    required:
    - password
    type: object
host: localhost:8080
info:
  contact: {}
  description: API Server for Internet Shop
  title: InternetShop
  version: "1.0"
paths:
  /ADDress:
    post:
      consumes:
      - application/json
      description: Create address
      parameters:
      - description: Address data
        in: body
        name: address
        required: true
        schema:
          $ref: '#/definitions/types.AddressPayload'
      produces:
      - application/json
      responses:
        "201":
          description: 'User with this ID: '
          schema:
            $ref: '#/definitions/responses.SuccessResponse'
      security:
      - ApiKeyAuth: []
      summary: Create Address
      tags:
      - Address
  /cart:
    delete:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: Del all products in you're cart
          schema:
            $ref: '#/definitions/responses.SuccessResponse'
      security:
      - ApiKeyAuth: []
      summary: full clear you're cart
      tags:
      - Cart
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: All products in cart
          schema:
            items:
              $ref: '#/definitions/types.CartItem'
            type: array
      security:
      - ApiKeyAuth: []
      summary: get cart
      tags:
      - Cart
    post:
      consumes:
      - application/json
      parameters:
      - description: Product Id, quantity
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/types.AddToCart'
      produces:
      - application/json
      responses:
        "200":
          description: success add
          schema:
            $ref: '#/definitions/responses.SuccessResponse'
      security:
      - ApiKeyAuth: []
      summary: add product in cart
      tags:
      - Cart
  /login:
    post:
      consumes:
      - application/json
      description: Log in user
      parameters:
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/types.UserLoginPayload'
      produces:
      - application/json
      responses:
        "200":
          description: Success login
          schema:
            $ref: '#/definitions/responses.JWTResponse'
      summary: log in
      tags:
      - Users
  /order:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "201":
          description: Success order
          schema:
            type: int
      security:
      - ApiKeyAuth: []
      summary: Create order
      tags:
      - Order
  /product/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Get one product with ID
          schema:
            $ref: '#/definitions/types.CreateProductPayload'
      summary: one product
      tags:
      - products
  /product/add:
    post:
      consumes:
      - application/json
      description: ONLY FOR ADMIN
      parameters:
      - description: Product data
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/types.AddProduct'
      produces:
      - application/json
      responses:
        "200":
          description: Product
          schema:
            $ref: '#/definitions/types.AddProduct'
      security:
      - ApiKeyAuth: []
      summary: addQuantityProduct
      tags:
      - Admin
  /product/create:
    post:
      consumes:
      - application/json
      description: ONLY FOR ADMIN
      parameters:
      - description: Product data
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/types.CreateProductPayload'
      produces:
      - application/json
      responses:
        "200":
          description: Product
          schema:
            $ref: '#/definitions/types.CreateProductPayload'
      security:
      - ApiKeyAuth: []
      summary: create new product
      tags:
      - Admin
  /products:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: Get all products
          schema:
            items:
              $ref: '#/definitions/types.ShortProducts'
            type: array
      summary: all products
      tags:
      - products
  /profile:
    delete:
      consumes:
      - application/json
      description: Full del acc with order, cart, address
      produces:
      - application/json
      responses:
        "200":
          description: 'Delete account:'
          schema:
            $ref: '#/definitions/responses.SuccessResponse'
      security:
      - ApiKeyAuth: []
      summary: Delete acc
      tags:
      - Users
    get:
      consumes:
      - application/json
      description: Profile for User
      produces:
      - application/json
      responses:
        "200":
          description: Get your profile
          schema:
            $ref: '#/definitions/types.UserProfile'
      security:
      - ApiKeyAuth: []
      summary: Get MY Profile
      tags:
      - Users
    patch:
      consumes:
      - application/json
      parameters:
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/types.UserUpdatePayload'
      produces:
      - application/json
      responses:
        "200":
          description: Success update
          schema:
            $ref: '#/definitions/responses.SuccessResponse'
      security:
      - ApiKeyAuth: []
      summary: Update Profile
      tags:
      - Users
  /register:
    post:
      consumes:
      - application/json
      description: Create someone user
      parameters:
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/types.UserRegisterPayload'
      produces:
      - application/json
      responses:
        "201":
          description: Success registration, but need confirm Email
          schema:
            $ref: '#/definitions/responses.UserRegisterResponse'
      summary: sign in
      tags:
      - Users
  /user/{id}:
    get:
      consumes:
      - application/json
      description: GET User ONLY FOR ADMIN
      parameters:
      - description: User data
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 'User with this ID: '
          schema:
            $ref: '#/definitions/types.User'
      security:
      - ApiKeyAuth: []
      summary: Get
      tags:
      - Admin
  /user/ban/{id}:
    post:
      consumes:
      - application/json
      description: Ban user
      parameters:
      - description: User id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 'User with this ID: '
          schema:
            $ref: '#/definitions/responses.SuccessResponse'
      security:
      - ApiKeyAuth: []
      summary: Post
      tags:
      - Admin
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
